/**
 * Unit tests for src/cli/lockfileFix.ts.
 *
 * We cover three tiers:
 *   1. Pure functions: `parseLockfileInstalledVersions` across npm v1/v2, pnpm v6/v9, yarn
 *      classic/berry; `diffLockfileTrees` for the merged / updated / added / removed cases.
 *   2. `dedupeCommandFor` — per-manager command selection and the yarn-classic skip.
 *   3. `runLockfileFix` orchestration against a temp dir: no-lockfile skip, unsupported skip,
 *      dry-run, and validator-rollback path (all without actually running `npm dedupe`).
 */
import assert from 'node:assert';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs/promises';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const {
  parseLockfileInstalledVersions,
  diffLockfileTrees,
  dedupeCommandFor,
  runLockfileFix,
} = await import(path.join(root, 'dist/cli/lockfileFix.js'));

function mapToSortedObject(m) {
  const out = {};
  for (const [k, v] of m) out[k] = [...v].sort();
  return out;
}

test('parseLockfileInstalledVersions: npm v2 `packages` map', () => {
  const raw = JSON.stringify({
    lockfileVersion: 2,
    packages: {
      '': { name: 'root' },
      'node_modules/axios': { version: '1.6.4' },
      'node_modules/axios/node_modules/form-data': { version: '4.0.0' },
      'node_modules/debug': { version: '4.3.4' },
      'node_modules/pkg/node_modules/debug': { version: '4.3.2' },
      'node_modules/@types/node': { version: '20.4.5' },
    },
  });
  const got = mapToSortedObject(parseLockfileInstalledVersions(raw, 'npm'));
  assert.deepStrictEqual(got, {
    axios: ['1.6.4'],
    'form-data': ['4.0.0'],
    debug: ['4.3.2', '4.3.4'],
    '@types/node': ['20.4.5'],
  });
});

test('parseLockfileInstalledVersions: npm v1 recursive `dependencies`', () => {
  const raw = JSON.stringify({
    lockfileVersion: 1,
    dependencies: {
      axios: {
        version: '1.6.4',
        dependencies: { 'form-data': { version: '4.0.0' } },
      },
      debug: { version: '4.3.4' },
    },
  });
  const got = mapToSortedObject(parseLockfileInstalledVersions(raw, 'npm'));
  assert.deepStrictEqual(got, {
    axios: ['1.6.4'],
    debug: ['4.3.4'],
    'form-data': ['4.0.0'],
  });
});

test('parseLockfileInstalledVersions: pnpm slashed + scoped keys', () => {
  const raw = [
    'lockfileVersion: 6.0',
    '',
    'packages:',
    '',
    '  /axios@1.6.4:',
    '    resolution: {integrity: sha-x}',
    '  /@types/node@20.4.5:',
    '    resolution: {integrity: sha-y}',
    "  /@babel/core@7.22.5(supports-color@5.5.0):",
    '    resolution: {integrity: sha-z}',
  ].join('\n');
  const got = mapToSortedObject(parseLockfileInstalledVersions(raw, 'pnpm'));
  assert.deepStrictEqual(got, {
    axios: ['1.6.4'],
    '@types/node': ['20.4.5'],
    '@babel/core': ['7.22.5'],
  });
});

test('parseLockfileInstalledVersions: yarn classic header + version lines', () => {
  const raw = [
    '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT.',
    '',
    '"axios@^1.6.0":',
    '  version "1.6.4"',
    '  resolved "https://registry.yarnpkg.com/axios/-/axios-1.6.4.tgz#sha"',
    '',
    '"@types/node@^20", "@types/node@^20.1.0":',
    '  version "20.4.5"',
    '',
    'debug@^4.3.0, debug@^4.3.4:',
    '  version "4.3.4"',
  ].join('\n');
  const got = mapToSortedObject(parseLockfileInstalledVersions(raw, 'yarn'));
  assert.deepStrictEqual(got, {
    axios: ['1.6.4'],
    '@types/node': ['20.4.5'],
    debug: ['4.3.4'],
  });
});

test('parseLockfileInstalledVersions: malformed input returns empty map without throwing', () => {
  const got = parseLockfileInstalledVersions('{not valid json', 'npm');
  assert.strictEqual(got.size, 0);
});

test('diffLockfileTrees: classifies merged / updated / added / removed', () => {
  const before = new Map([
    ['debug', new Set(['4.3.2', '4.3.4'])], // merged
    ['axios', new Set(['1.6.0'])], // updated
    ['gone', new Set(['1.0.0'])], // removed
    ['same', new Set(['2.0.0'])], // no-op (filtered out)
  ]);
  const after = new Map([
    ['debug', new Set(['4.3.4'])],
    ['axios', new Set(['1.6.4'])],
    ['same', new Set(['2.0.0'])],
    ['new-dep', new Set(['0.1.0'])], // added
  ]);
  const diff = diffLockfileTrees(before, after);
  const byName = Object.fromEntries(diff.map((c) => [c.name, c]));
  assert.deepStrictEqual(byName.debug.change, 'merged');
  assert.deepStrictEqual(byName.debug.before, ['4.3.2', '4.3.4']);
  assert.deepStrictEqual(byName.debug.after, ['4.3.4']);
  assert.strictEqual(byName.axios.change, 'updated');
  assert.strictEqual(byName['new-dep'].change, 'added');
  assert.strictEqual(byName.gone.change, 'removed');
  assert.ok(!byName.same, 'no-op rows must be filtered out');
  // Sort order: merged → updated → added → removed.
  assert.deepStrictEqual(diff.map((c) => c.change), ['merged', 'updated', 'added', 'removed']);
});

test('dedupeCommandFor: per-manager + yarn-classic returns undefined', () => {
  assert.deepStrictEqual(dedupeCommandFor('pnpm'), { bin: 'pnpm', args: ['dedupe'] });
  assert.deepStrictEqual(dedupeCommandFor('npm'), {
    bin: 'npm',
    args: ['dedupe', '--no-audit', '--loglevel', 'error'],
  });
  assert.deepStrictEqual(dedupeCommandFor('yarn', { yarnMajorVersion: 3 }), {
    bin: 'yarn',
    args: ['dedupe'],
  });
  assert.strictEqual(dedupeCommandFor('yarn', { yarnMajorVersion: 1 }), undefined);
  assert.strictEqual(dedupeCommandFor('yarn'), undefined, 'default (no version) = classic');
});

test('runLockfileFix: skips with no-lockfile reason when lockfile missing', async () => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'dus-lockfix-'));
  await fs.writeFile(path.join(dir, 'package.json'), '{}');
  const r = await runLockfileFix({ cwd: dir, manager: 'npm', json: true });
  assert.strictEqual(r.report.status, 'skipped');
  assert.strictEqual(r.report.skipReason, 'no-lockfile');
  assert.strictEqual(r.report.manager, 'npm');
  assert.deepStrictEqual(r.report.dedupeChanges, []);
});

test('runLockfileFix: skips with unsupported reason on yarn classic', async () => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'dus-lockfix-'));
  await fs.writeFile(path.join(dir, 'package.json'), '{}');
  await fs.writeFile(path.join(dir, 'yarn.lock'), '# classic lockfile\n');
  const r = await runLockfileFix({
    cwd: dir,
    manager: 'yarn',
    yarnMajorVersion: 1,
    json: true,
  });
  assert.strictEqual(r.report.status, 'skipped');
  assert.strictEqual(r.report.skipReason, 'unsupported');
});

test('runLockfileFix: dry-run returns the command but never exec', async () => {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'dus-lockfix-'));
  await fs.writeFile(path.join(dir, 'package.json'), '{}');
  await fs.writeFile(
    path.join(dir, 'package-lock.json'),
    JSON.stringify({ lockfileVersion: 2, packages: {} }),
  );
  const r = await runLockfileFix({
    cwd: dir,
    manager: 'npm',
    json: true,
    dryRun: true,
  });
  assert.strictEqual(r.report.status, 'dry-run');
  assert.match(r.report.command ?? '', /^npm dedupe /);
  assert.deepStrictEqual(r.report.dedupeChanges, []);
});
