/**
 * Unit tests for src/cli/outdated.ts. Registry lookups go through a pre-seeded `RegistryCache`
 * so nothing touches the network.
 */
import assert from 'node:assert';
import test from 'node:test';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import os from 'node:os';
import fs from 'node:fs/promises';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..', '..');
const { runOutdated, renderOutdatedHuman, outdatedExitCode } = await import(
  path.join(root, 'dist/cli/outdated.js')
);
const { createRegistryCache } = await import(path.join(root, 'dist/utils/concurrency.js'));

async function mkProject(entries) {
  const dir = await fs.mkdtemp(path.join(os.tmpdir(), 'dus-outdated-'));
  for (const [rel, contents] of Object.entries(entries)) {
    await fs.writeFile(path.join(dir, rel), contents);
  }
  return dir;
}

function seededCache(entries) {
  const cache = createRegistryCache();
  for (const [name, latest] of Object.entries(entries)) {
    if (latest instanceof Error) {
      const p = Promise.reject(latest);
      p.catch(() => {});
      cache.latest.set(name, p);
    } else {
      cache.latest.set(name, Promise.resolve(latest));
    }
  }
  return cache;
}

test('outdatedExitCode: 2 when no package could be checked, 1 when outdated, 0 otherwise', () => {
  const row = (status, extra = {}) => ({ name: 'x', section: 'dependencies', declared: '^1.0.0', status, ...extra });
  const report = (rows) => ({
    cwd: '/repo',
    manager: 'npm',
    rows,
    summary: {
      total: rows.length,
      outdated: rows.filter((r) => r.status === 'outdated').length,
      upToDate: rows.filter((r) => r.status === 'up-to-date').length,
      ahead: 0,
      unknown: rows.filter((r) => r.status === 'unknown').length,
    },
  });
  assert.strictEqual(outdatedExitCode(report([row('unknown', { error: 'ENOTFOUND' }), row('unknown', { error: 'ENOTFOUND' })])), 2);
  assert.strictEqual(outdatedExitCode(report([row('unknown', { error: 'ENOTFOUND' }), row('outdated')])), 1);
  assert.strictEqual(outdatedExitCode(report([row('unknown', { error: 'ENOTFOUND' }), row('up-to-date')])), 0);
  assert.strictEqual(outdatedExitCode(report([])), 0);
});

test('runOutdated: every registry lookup failing → errors listed and exit code 2', async () => {
  const dir = await mkProject({
    'package.json': JSON.stringify({ name: 'app', dependencies: { lodash: '^4.17.0', debug: '^4.3.0' } }),
  });
  const offline = new Error('request to https://registry.npmjs.org/lodash failed, reason: getaddrinfo ENOTFOUND registry.npmjs.org');
  const report = await runOutdated({
    cwd: dir,
    registryCache: seededCache({ lodash: offline, debug: offline }),
  });
  assert.strictEqual(report.summary.unknown, 2);
  assert.ok(report.rows.every((r) => /ENOTFOUND/.test(r.error ?? '')));
  assert.strictEqual(outdatedExitCode(report), 2);
  const human = renderOutdatedHuman(report);
  assert.match(human, /ENOTFOUND/);
  assert.match(human, /no package could be checked/i);
});

test('runOutdated: yarn berry lockfile version is used (no false "outdated")', async () => {
  const dir = await mkProject({
    'package.json': JSON.stringify({ name: 'app', packageManager: 'yarn@4.5.3', dependencies: { lodash: '^4.17.0' } }),
    'yarn.lock': [
      '# This file is generated by running "yarn install" inside your project.',
      '# Manual changes might be lost - proceed with caution!',
      '',
      '__metadata:',
      '  version: 8',
      '  cacheKey: 10c0',
      '',
      '"app@workspace:.":',
      '  version: 0.0.0-use.local',
      '  resolution: "app@workspace:."',
      '  dependencies:',
      '    lodash: "npm:^4.17.0"',
      '  languageName: unknown',
      '  linkType: soft',
      '',
      '"lodash@npm:^4.17.0":',
      '  version: 4.17.21',
      '  resolution: "lodash@npm:4.17.21"',
      '  checksum: 10c0/d8cbea072bb08655bb4c989da418994b073a608dffa608b09ac04b43a791b12aeae7cd7ad919aa4c925f33b48490b5cfe6c1f71d827956071dae2e7bb3a6b74c',
      '  languageName: node',
      '  linkType: hard',
      '',
    ].join('\n'),
  });
  const report = await runOutdated({ cwd: dir, registryCache: seededCache({ lodash: '4.17.21' }) });
  const lodash = report.rows.find((r) => r.name === 'lodash');
  assert.strictEqual(lodash.installed, '4.17.21');
  assert.strictEqual(lodash.status, 'up-to-date');
  assert.strictEqual(outdatedExitCode(report), 0);
});

test('runOutdated: a nested newer copy does not hide an outdated direct dependency', async () => {
  const dir = await mkProject({
    'package.json': JSON.stringify({ name: 'app', dependencies: { debug: '^2.6.9', send: '^1.1.0' } }),
    'package-lock.json': JSON.stringify({
      name: 'app',
      lockfileVersion: 3,
      requires: true,
      packages: {
        '': { name: 'app', dependencies: { debug: '^2.6.9', send: '^1.1.0' } },
        'node_modules/debug': { version: '2.6.9', dependencies: { ms: '2.0.0' } },
        'node_modules/ms': { version: '2.0.0' },
        'node_modules/send': { version: '1.1.0', dependencies: { debug: '^4.3.5' } },
        'node_modules/send/node_modules/debug': { version: '4.4.0' },
      },
    }),
  });
  const report = await runOutdated({
    cwd: dir,
    registryCache: seededCache({ debug: '4.4.0', send: '1.1.0' }),
  });
  const debug = report.rows.find((r) => r.name === 'debug');
  assert.strictEqual(debug.installed, '2.6.9');
  assert.strictEqual(debug.status, 'outdated');
  assert.strictEqual(outdatedExitCode(report), 1);
});
